/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_seandroid_manager_KLogCtl */

#ifndef _Included_com_android_seandroid_manager_KLogCtl
#define _Included_com_android_seandroid_manager_KLogCtl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_seandroid_manager_KLogCtl
 * Method:    kLogCtl
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_android_seandroid_1manager_KLogCtl_kLogCtl
  (JNIEnv *, jclass, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif

